package com.medicita.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdjuntoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdjuntoAllPropertiesEquals(Adjunto expected, Adjunto actual) {
        assertAdjuntoAutoGeneratedPropertiesEquals(expected, actual);
        assertAdjuntoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdjuntoAllUpdatablePropertiesEquals(Adjunto expected, Adjunto actual) {
        assertAdjuntoUpdatableFieldsEquals(expected, actual);
        assertAdjuntoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdjuntoAutoGeneratedPropertiesEquals(Adjunto expected, Adjunto actual) {
        assertThat(actual)
            .as("Verify Adjunto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdjuntoUpdatableFieldsEquals(Adjunto expected, Adjunto actual) {
        assertThat(actual)
            .as("Verify Adjunto relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getContenido()).as("check contenido").isEqualTo(expected.getContenido()))
            .satisfies(a ->
                assertThat(a.getContenidoContentType()).as("check contenido contenty type").isEqualTo(expected.getContenidoContentType())
            )
            .satisfies(a -> assertThat(a.getTipoContenido()).as("check tipoContenido").isEqualTo(expected.getTipoContenido()))
            .satisfies(a -> assertThat(a.getFechaSubida()).as("check fechaSubida").isEqualTo(expected.getFechaSubida()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdjuntoUpdatableRelationshipsEquals(Adjunto expected, Adjunto actual) {
        assertThat(actual)
            .as("Verify Adjunto relationships")
            .satisfies(a -> assertThat(a.getCita()).as("check cita").isEqualTo(expected.getCita()))
            .satisfies(a -> assertThat(a.getHistoriaClinica()).as("check historiaClinica").isEqualTo(expected.getHistoriaClinica()));
    }
}
