package com.medicita.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContenidoWebAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenidoWebAllPropertiesEquals(ContenidoWeb expected, ContenidoWeb actual) {
        assertContenidoWebAutoGeneratedPropertiesEquals(expected, actual);
        assertContenidoWebAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenidoWebAllUpdatablePropertiesEquals(ContenidoWeb expected, ContenidoWeb actual) {
        assertContenidoWebUpdatableFieldsEquals(expected, actual);
        assertContenidoWebUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenidoWebAutoGeneratedPropertiesEquals(ContenidoWeb expected, ContenidoWeb actual) {
        assertThat(actual)
            .as("Verify ContenidoWeb auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenidoWebUpdatableFieldsEquals(ContenidoWeb expected, ContenidoWeb actual) {
        assertThat(actual)
            .as("Verify ContenidoWeb relevant properties")
            .satisfies(a -> assertThat(a.getClave()).as("check clave").isEqualTo(expected.getClave()))
            .satisfies(a -> assertThat(a.getValorTexto()).as("check valorTexto").isEqualTo(expected.getValorTexto()))
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()))
            .satisfies(a -> assertThat(a.getImagenContentType()).as("check imagen contenty type").isEqualTo(expected.getImagenContentType())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenidoWebUpdatableRelationshipsEquals(ContenidoWeb expected, ContenidoWeb actual) {
        // empty method
    }
}
