package com.medicita.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisponibilidadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisponibilidadAllPropertiesEquals(Disponibilidad expected, Disponibilidad actual) {
        assertDisponibilidadAutoGeneratedPropertiesEquals(expected, actual);
        assertDisponibilidadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisponibilidadAllUpdatablePropertiesEquals(Disponibilidad expected, Disponibilidad actual) {
        assertDisponibilidadUpdatableFieldsEquals(expected, actual);
        assertDisponibilidadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisponibilidadAutoGeneratedPropertiesEquals(Disponibilidad expected, Disponibilidad actual) {
        assertThat(actual)
            .as("Verify Disponibilidad auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisponibilidadUpdatableFieldsEquals(Disponibilidad expected, Disponibilidad actual) {
        assertThat(actual)
            .as("Verify Disponibilidad relevant properties")
            .satisfies(a -> assertThat(a.getDia()).as("check dia").isEqualTo(expected.getDia()))
            .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
            .satisfies(a -> assertThat(a.getHoraFin()).as("check horaFin").isEqualTo(expected.getHoraFin()))
            .satisfies(a -> assertThat(a.getEsDescanso()).as("check esDescanso").isEqualTo(expected.getEsDescanso()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisponibilidadUpdatableRelationshipsEquals(Disponibilidad expected, Disponibilidad actual) {
        assertThat(actual)
            .as("Verify Disponibilidad relationships")
            .satisfies(a -> assertThat(a.getMedico()).as("check medico").isEqualTo(expected.getMedico()));
    }
}
